// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type NewProduct struct {
	Name  string `json:"name"`
	Price int32  `json:"price"`
	Stock int32  `json:"stock"`
}

type NewUser struct {
	Name  string `json:"name"`
	Email string `json:"email"`
}

type Products struct {
	ID    string `json:"_id"`
	Name  string `json:"name"`
	Price int32  `json:"price"`
	Stock int32  `json:"stock"`
}

type Query struct {
}

type Users struct {
	ID    string `json:"_id"`
	Name  string `json:"name"`
	Email string `json:"email"`
}
